-- 1.

SELECT * FROM CITY
WHERE POPULATION > 100000 AND COUNTRYCODE = 'USA';

-- 2.

SELECT NAME FROM CITY
WHERE POPULATION > 120000 AND COUNTRYCODE = 'USA';

-- 3.

SELECT * FROM CITY;

-- 4.

SELECT * FROM CITY
WHERE ID = 1661;

-- 5.

SELECT * FROM CITY
WHERE COUNTRYCODE = 'JPN';

-- 6.

SELECT NAME FROM CITY
WHERE COUNTRYCODE = 'JPN';

-- 7.

SELECT CITY, STATE FROM STATION;

-- 8.

SELECT DISTINCT CITY FROM STATION 
WHERE ID % 2 = 0

-- 9.

SELECT CITY, LENGTH(CITY) FROM STATION
ORDER BY LENGTH(CITY) ASC, CITY ASC
LIMIT 1;

SELECT CITY, LENGTH(CITY) FROM STATION
ORDER BY LENGTH(CITY) DESC, CITY DESC
LIMIT 1;

--10.

SELECT DISTINCT CITY
FROM STATION
WHERE CITY LIKE '%a'
   OR CITY LIKE '%e' 
   OR CITY LIKE '%i'
   OR CITY LIKE '%o'
   OR CITY LIKE '%u'

--11.

SELECT DISTINCT CITY
FROM STATION
WHERE (CITY LIKE 'a%' OR CITY LIKE 'e%' OR CITY LIKE 'i%' OR CITY LIKE 'o%' OR CITY LIKE 'u%')
  AND (CITY LIKE '%a' OR CITY LIKE '%e' OR CITY LIKE '%i' OR CITY LIKE '%o' OR CITY LIKE '%u')

--12.

SELECT DISTINCT CITY
FROM STATION
WHERE CITY NOT LIKE 'a%'
  AND CITY NOT LIKE 'e%' 
  AND CITY NOT LIKE 'i%'
  AND CITY NOT LIKE 'o%'
  AND CITY NOT LIKE 'u%'
ORDER BY CITY
